# Generated by Django 4.0.4 on 2022-09-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
