# Generated by Django 4.0.4 on 2022-09-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_post_preview_post_titlebreak1_post_titlebreak2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titleBreak1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='titleBreak2',
            field=models.CharField(max_length=200),
        ),
    ]
