# Generated by Django 4.0.4 on 2022-10-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='pics/'),
        ),
    ]
