# Generated by Django 4.0.4 on 2022-10-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_alter_post_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='background_image',
        ),
        migrations.AddField(
            model_name='post',
            name='bgimage',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
