# Generated by Django 4.0.4 on 2022-10-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_remove_post_background_image_post_bgimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=200, null=True, unique=True),
        ),
    ]
