# Generated by Django 4.0.4 on 2023-01-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titleBreak1',
            field=models.TextField(max_length=200),
        ),
    ]
