# Generated by Django 4.0.4 on 2023-01-18 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0019_alter_post_titlebreak1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='titleBreak2',
            new_name='pic_owner',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='titleBreak1',
            new_name='titleBreak',
        ),
    ]
