# Generated by Django 4.0.4 on 2023-01-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0020_rename_titlebreak2_post_pic_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hyperlink',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
